# Generated by Django 5.1.6 on 2025-03-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
    ]
