# Generated by Django 5.1.6 on 2025-03-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_faculty_office_hours_course_default_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(max_length=20)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academics.classsection')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academics.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academics.faculty')),
            ],
            options={
                'unique_together': {('class_section', 'day', 'start_time'), ('faculty', 'day', 'start_time'), ('room_number', 'day', 'start_time')},
            },
        ),
    ]
